# make -f Makefile_pdflatex

R = clustering
R2 = csm
STY = *.cls
FIG = 

pdf: $(R).pdf

$(R).bbl: $(R2).bib
	pdflatex $(R)
	bibtex $(R)
	pdflatex $(R)

$(R).pdf: *.tex $(STY) $(FIG) $(R).bbl
	pdflatex $(R)

clean:
	rm -f $(R).log $(R).aux $(R).bbl $(R).blg $(R).out
